import Link from "next/link";
import { Sparkles } from "lucide-react";

// First component in components/ui/ -- small, cross-feature UI primitives
// belong here rather than in a feature directory (journal/, portfolio/, ...).

/**
 * Clickable pill marking content the system generated rather than the user
 * typed -- currently the trade journal's post-mortem `outcome` narrative
 * (services/trade_postmortem.py). Links to the Cost & Budget page
 * (app/usage/page.tsx) so a click-through lands on the spend/model that
 * produced it.
 */
export function AiGeneratedBadge({ className = "" }: { className?: string }) {
    return (
        <Link
            href="/usage"
            prefetch={false}
            title="Generated by the post-mortem LLM pass -- view AI cost & budget"
            className={`inline-flex items-center gap-1.5 rounded-lg border border-violet-200 bg-violet-50 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-violet-700 transition-colors hover:border-violet-300 hover:bg-violet-100 dark:border-violet-900/40 dark:bg-violet-950/30 dark:text-violet-300 dark:hover:border-violet-700 dark:hover:bg-violet-950/50 ${className}`}
        >
            <Sparkles className="h-3 w-3" />
            AI Generated
        </Link>
    );
}
