// Unmock fs-extra since workspace env tests need real filesystem access
jest.unmock('fs-extra');

import * as os from 'os';
import * as path from 'path';
import * as fs from 'fs-extra';
import { Command } from 'commander';
import extension, {
  EnvManifest,
  parseEnvContent,
  syncWorkspaceEnv,
  validateWorkspaceEnv
} from '../extensions/workspace-env/index';

let tmpDir: string;

beforeEach(async () => {
  tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'workspace-env-test-'));
});

afterEach(async () => {
  if (tmpDir && await fs.pathExists(tmpDir)) {
    await fs.remove(tmpDir);
  }
});

describe('workspace-env extension helpers', () => {
  it('parses dotenv content and ignores comments', () => {
    const parsed = parseEnvContent(`# comment\nexport API_URL=https://api.example.com\n\nEMPTY=\nQUOTED="value"\n`);

    expect(parsed.API_URL).toBe('https://api.example.com');
    expect(parsed.EMPTY).toBe('');
    expect(parsed.QUOTED).toBe('value');
  });

  it('syncs target env files and generates examples', async () => {
    await fs.writeFile(path.join(tmpDir, '.env'), 'API_BASE_URL=https://api.example.com\nSHARED_TOKEN=topsecret\n');

    const manifest: EnvManifest = {
      sources: ['.env'],
      targets: {
        landing: { path: 'apps/landing' }
      },
      variables: {
        API_BASE_URL: {
          description: 'Base URL',
          required: true,
          targets: { landing: 'NEXT_PUBLIC_API_BASE_URL' }
        },
        SHARED_TOKEN: {
          description: 'Private token',
          secret: true,
          required: true,
          targets: { landing: 'SHARED_TOKEN' }
        }
      }
    };

    const summary = await syncWorkspaceEnv(tmpDir, manifest);
    expect(summary.missingRequired).toHaveLength(0);
    expect(summary.sourceFiles).toEqual(['.env']);

    const targetEnv = await fs.readFile(path.join(tmpDir, 'apps/landing/.env.local'), 'utf-8');
    expect(targetEnv).toContain('Generated by @edcalderon/versioning workspace-env');
    expect(targetEnv).toContain('NEXT_PUBLIC_API_BASE_URL=https://api.example.com');
    expect(targetEnv).toContain('SHARED_TOKEN=topsecret');

    const targetExample = await fs.readFile(path.join(tmpDir, 'apps/landing/.env.example'), 'utf-8');
    expect(targetExample).toContain('NEXT_PUBLIC_API_BASE_URL=https://api.example.com');
    expect(targetExample).toContain('SHARED_TOKEN=');

    const rootExample = await fs.readFile(path.join(tmpDir, '.env.example'), 'utf-8');
    expect(rootExample).toContain('API_BASE_URL=https://api.example.com');
  });

  it('validates missing required variables and unknown root keys', async () => {
    await fs.writeFile(path.join(tmpDir, '.env'), 'UNKNOWN_THING=yes\n');

    const manifest: EnvManifest = {
      sources: ['.env'],
      targets: {
        landing: { path: 'apps/landing' }
      },
      variables: {
        API_BASE_URL: {
          required: true,
          targets: { landing: 'NEXT_PUBLIC_API_BASE_URL' }
        }
      }
    };

    const result = await validateWorkspaceEnv(tmpDir, manifest);
    expect(result.ok).toBe(false);
    expect(result.missingRequiredByTarget.landing).toContain('API_BASE_URL');
    expect(result.unknownRootKeys).toContain('UNKNOWN_THING');
  });

  it('supports the spec-style manifest shape and target-level required flags', async () => {
    await fs.writeFile(path.join(tmpDir, '.env'), 'SUPABASE_URL=https://db.example.com\nLEGACY_OPENAI_KEY=legacy-secret\n');

    const manifest: EnvManifest = {
      rootExampleFile: 'config/env/root.example',
      variables: [
        {
          key: 'SUPABASE_URL',
          description: 'Supabase URL'
        },
        {
          key: 'OPENAI_API_KEY',
          aliases: ['LEGACY_OPENAI_KEY'],
          description: 'OpenAI key',
          secret: true
        }
      ],
      targets: [
        {
          id: 'landing',
          outputFile: 'apps/landing/.env.local',
          exampleFile: 'apps/landing/.env.example',
          entries: [
            {
              source: 'SUPABASE_URL',
              target: 'NEXT_PUBLIC_SUPABASE_URL',
              required: true
            },
            {
              source: 'OPENAI_API_KEY',
              required: false
            }
          ]
        }
      ]
    };

    const summary = await syncWorkspaceEnv(tmpDir, manifest);
    expect(summary.missingRequired).toEqual([]);

    const targetEnv = await fs.readFile(path.join(tmpDir, 'apps/landing/.env.local'), 'utf-8');
    expect(targetEnv).toContain('NEXT_PUBLIC_SUPABASE_URL=https://db.example.com');
    expect(targetEnv).toContain('OPENAI_API_KEY=legacy-secret');

    const targetExample = await fs.readFile(path.join(tmpDir, 'apps/landing/.env.example'), 'utf-8');
    expect(targetExample).toContain('NEXT_PUBLIC_SUPABASE_URL=https://db.example.com');
    expect(targetExample).toContain('OPENAI_API_KEY=');

    const rootExample = await fs.readFile(path.join(tmpDir, 'config/env/root.example'), 'utf-8');
    expect(rootExample).toContain('SUPABASE_URL=https://db.example.com');
    expect(rootExample).toContain('OPENAI_API_KEY=');
  });

  it('reports ready targets and unused known root keys', async () => {
    await fs.writeFile(path.join(tmpDir, '.env'), 'API_BASE_URL=https://api.example.com\nROOT_ONLY=yes\n');

    const manifest: EnvManifest = {
      sources: ['.env'],
      variables: [
        {
          key: 'API_BASE_URL'
        },
        {
          key: 'ROOT_ONLY'
        }
      ],
      targets: [
        {
          id: 'dashboard',
          outputFile: 'apps/dashboard/.env.local',
          exampleFile: 'apps/dashboard/.env.example',
          entries: [
            {
              source: 'API_BASE_URL',
              target: 'NEXT_PUBLIC_API_BASE_URL',
              required: true
            }
          ]
        }
      ]
    };

    const result = await validateWorkspaceEnv(tmpDir, manifest);
    expect(result.ok).toBe(true);
    expect(result.readyTargets).toContain('dashboard');
    expect(result.unusedRootKeys).toContain('ROOT_ONLY');
  });

  it('supports check-only sync without writing files', async () => {
    await fs.writeFile(path.join(tmpDir, '.env'), 'API_BASE_URL=https://api.example.com\n');

    const manifest: EnvManifest = {
      sources: ['.env'],
      targets: {
        landing: { path: 'apps/landing' }
      },
      variables: {
        API_BASE_URL: {
          required: true,
          targets: { landing: 'NEXT_PUBLIC_API_BASE_URL' }
        }
      }
    };

    const preview = await syncWorkspaceEnv(tmpDir, manifest, { checkOnly: true });
    expect(preview.changedFiles).toContain('apps/landing/.env.local');
    expect(await fs.pathExists(path.join(tmpDir, 'apps/landing/.env.local'))).toBe(false);

    await syncWorkspaceEnv(tmpDir, manifest);
    const secondPreview = await syncWorkspaceEnv(tmpDir, manifest, { checkOnly: true });
    expect(secondPreview.changedFiles).toEqual([]);
    expect(secondPreview.unchangedFiles).toContain('apps/landing/.env.local');
  });
});

describe('workspace-env command registration', () => {
  it('registers env command with sync/doctor/validate subcommands', async () => {
    const program = new Command();
    await extension.register(program, {});

    const env = program.commands.find((command) => command.name() === 'env');
    expect(env).toBeDefined();
    expect(env?.commands.map((command) => command.name())).toEqual(
      expect.arrayContaining(['sync', 'doctor', 'validate'])
    );
  });
});