import { Command } from 'commander';
import * as fs from 'fs-extra';
import * as path from 'path';
import { VersioningExtension } from '../../extensions';

export interface EnvTargetConfig {
  path: string;
  envFile?: string;
  exampleFile?: string;
  description?: string;
}

export interface EnvVariableConfig {
  aliases?: string[];
  description?: string;
  secret?: boolean;
  required?: boolean;
  example?: string;
  targets?: Record<string, string>;
}

export interface EnvVariableDefinition {
  key: string;
  aliases?: string[];
  description?: string;
  example?: string;
  secret?: boolean;
}

export interface EnvTargetEntry {
  source: string;
  target?: string;
  required?: boolean;
}

export interface EnvTargetDefinition {
  id: string;
  description?: string;
  outputFile: string;
  exampleFile: string;
  entries: EnvTargetEntry[];
}

export interface LegacyEnvManifest {
  sources?: string[];
  rootExampleFile?: string;
  variables: Record<string, EnvVariableConfig>;
  targets: Record<string, EnvTargetConfig>;
}

export interface SpecEnvManifest {
  sources?: string[];
  rootExampleFile?: string;
  variables: EnvVariableDefinition[];
  targets: EnvTargetDefinition[];
}

export type EnvManifest = LegacyEnvManifest | SpecEnvManifest;

export interface WorkspaceEnvConfig {
  enabled?: boolean;
  manifestPath?: string;
}

export interface SyncSummary {
  sourceFiles: string[];
  touchedFiles: string[];
  changedFiles: string[];
  unchangedFiles: string[];
  missingRequired: string[];
}

export interface ValidationResult {
  ok: boolean;
  sourceFiles: string[];
  readyTargets: string[];
  missingRequiredByTarget: Record<string, string[]>;
  unknownRootKeys: string[];
  unusedRootKeys: string[];
}

interface NormalizedVariable {
  key: string;
  aliases: string[];
  description?: string;
  example?: string;
  secret?: boolean;
}

interface NormalizedTargetEntry {
  source: string;
  target: string;
  required: boolean;
}

interface NormalizedTarget {
  id: string;
  description?: string;
  outputFile: string;
  exampleFile: string;
  entries: NormalizedTargetEntry[];
}

interface NormalizedManifest {
  sources: string[];
  rootExampleFile: string;
  variables: Record<string, NormalizedVariable>;
  targets: Record<string, NormalizedTarget>;
}

interface WorkspaceAnalysis {
  manifest: NormalizedManifest;
  rootValues: Record<string, string>;
  sourceFiles: string[];
  selectedTargets: string[];
  readyTargets: string[];
  missingRequiredByTarget: Record<string, string[]>;
  unknownRootKeys: string[];
  unusedRootKeys: string[];
}

const DEFAULT_MANIFEST_CANDIDATES = [
  'config/env/manifest.ts',
  'config/env/manifest.cjs',
  'config/env/manifest.js',
  'config/env/manifest.json'
];

const GENERATED_HEADER = 'Generated by @edcalderon/versioning workspace-env. Do not edit directly.';

export function parseEnvContent(content: string): Record<string, string> {
  const values: Record<string, string> = {};
  const lines = content.split(/\r?\n/);

  for (const line of lines) {
    const trimmed = line.trim().replace(/^export\s+/, '');
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIndex = trimmed.indexOf('=');
    if (eqIndex <= 0) continue;

    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

export async function loadRootEnv(rootDir: string, sources: string[]): Promise<Record<string, string>> {
  const merged: Record<string, string> = {};

  for (const source of sources) {
    const sourcePath = path.resolve(rootDir, source);
    if (!(await fs.pathExists(sourcePath))) continue;

    const content = await fs.readFile(sourcePath, 'utf-8');
    const parsed = parseEnvContent(content);

    Object.assign(merged, parsed);
  }

  return merged;
}

export function resolveManifestPath(rootDir: string, configuredPath?: string): string {
  if (configuredPath) {
    return path.resolve(rootDir, configuredPath);
  }

  for (const candidate of DEFAULT_MANIFEST_CANDIDATES) {
    const candidatePath = path.resolve(rootDir, candidate);
    if (fs.existsSync(candidatePath)) {
      return candidatePath;
    }
  }

  throw new Error(
    `Workspace env manifest not found. Searched: ${DEFAULT_MANIFEST_CANDIDATES.join(', ')}. ` +
      'Set extensionConfig["workspace-env"].manifestPath in versioning.config.json to customize the location.'
  );
}

export async function loadManifest(manifestPath: string): Promise<EnvManifest> {
  const ext = path.extname(manifestPath).toLowerCase();

  if (ext === '.json') {
    return await fs.readJson(manifestPath);
  }

  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const required = require(manifestPath);
    return required.default || required;
  } catch (error) {
    if (ext === '.ts') {
      throw new Error(
        `Unable to load TypeScript manifest at ${manifestPath}. Use .cjs, .js, or .json, or ensure your runtime can require TypeScript files.`
      );
    }
    throw error;
  }
}

function isSpecManifest(manifest: EnvManifest): manifest is SpecEnvManifest {
  return Array.isArray((manifest as SpecEnvManifest).variables);
}

function normalizeManifest(manifest: EnvManifest): NormalizedManifest {
  const sources = sortedUnique((manifest.sources || ['.env', '.env.local']).map((source) => source.trim()).filter(Boolean));
  const rootExampleFile = 'rootExampleFile' in manifest && manifest.rootExampleFile
    ? manifest.rootExampleFile
    : '.env.example';

  if (isSpecManifest(manifest)) {
    const variables: Record<string, NormalizedVariable> = {};
    for (const variable of manifest.variables) {
      variables[variable.key] = {
        key: variable.key,
        aliases: sortedUnique(variable.aliases || []),
        description: variable.description,
        example: variable.example,
        secret: variable.secret
      };
    }

    const targets: Record<string, NormalizedTarget> = {};
    for (const target of manifest.targets) {
      const entries = target.entries.map((entry) => {
        if (!variables[entry.source]) {
          throw new Error(`workspace-env target "${target.id}" references unknown variable "${entry.source}"`);
        }

        return {
          source: entry.source,
          target: entry.target || entry.source,
          required: entry.required === true
        };
      });

      targets[target.id] = {
        id: target.id,
        description: target.description,
        outputFile: target.outputFile,
        exampleFile: target.exampleFile,
        entries: sortEntries(entries)
      };
    }

    return {
      sources,
      rootExampleFile,
      variables,
      targets: sortTargets(targets)
    };
  }

  const variables: Record<string, NormalizedVariable> = {};
  for (const key of Object.keys(manifest.variables || {}).sort()) {
    const variable = manifest.variables[key];
    variables[key] = {
      key,
      aliases: sortedUnique(variable.aliases || []),
      description: variable.description,
      example: variable.example,
      secret: variable.secret
    };
  }

  const targets: Record<string, NormalizedTarget> = {};
  for (const targetId of Object.keys(manifest.targets || {}).sort()) {
    const target = manifest.targets[targetId];
    const entries: NormalizedTargetEntry[] = [];

    for (const key of Object.keys(manifest.variables || {}).sort()) {
      const variable = manifest.variables[key];
      const mappedKey = variable.targets?.[targetId];
      if (!mappedKey) continue;

      entries.push({
        source: key,
        target: mappedKey,
        required: variable.required === true
      });
    }

    targets[targetId] = {
      id: targetId,
      description: target.description,
      outputFile: path.join(target.path, target.envFile || '.env.local'),
      exampleFile: path.join(target.path, target.exampleFile || '.env.example'),
      entries: sortEntries(entries)
    };
  }

  return {
    sources,
    rootExampleFile,
    variables,
    targets: sortTargets(targets)
  };
}

function pickCanonicalValue(
  canonicalKey: string,
  variable: NormalizedVariable,
  rootValues: Record<string, string>
): string | undefined {
  if (rootValues[canonicalKey] !== undefined) return rootValues[canonicalKey];

  for (const alias of variable.aliases || []) {
    if (rootValues[alias] !== undefined) return rootValues[alias];
  }

  return undefined;
}

function formatEnvFile(
  entries: Array<{ key: string; value: string; description?: string }>,
  fileLabel: string
): string {
  const lines: string[] = [`# ${GENERATED_HEADER}`, `# ${fileLabel}`, ''];

  for (const entry of entries) {
    if (entry.description) {
      lines.push(`# ${entry.description}`);
    }
    lines.push(`${entry.key}=${entry.value}`);
  }

  return `${lines.join('\n')}\n`;
}

async function writeIfChanged(filePath: string, content: string, checkOnly = false): Promise<boolean> {
  const exists = await fs.pathExists(filePath);
  if (exists) {
    const current = await fs.readFile(filePath, 'utf-8');
    if (current === content) return false;
  }

  if (checkOnly) {
    return true;
  }

  await fs.ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, content, 'utf-8');
  return true;
}

function getRelevantTargets(manifest: NormalizedManifest, targetFilter?: string[]): string[] {
  const allTargets = Object.keys(manifest.targets || {}).sort();
  if (!targetFilter || targetFilter.length === 0) return allTargets;

  const selected = new Set(targetFilter);
  return allTargets.filter((target) => selected.has(target));
}

function sortedUnique(values: string[]): string[] {
  return Array.from(new Set(values)).sort();
}

function sortEntries(entries: NormalizedTargetEntry[]): NormalizedTargetEntry[] {
  return [...entries].sort((left, right) => left.target.localeCompare(right.target));
}

function sortTargets(targets: Record<string, NormalizedTarget>): Record<string, NormalizedTarget> {
  return Object.fromEntries(Object.entries(targets).sort(([left], [right]) => left.localeCompare(right)));
}

function collectTargetOption(value: string, previous: string[] = []): string[] {
  const nextValues = value
    .split(',')
    .map((target) => target.trim())
    .filter(Boolean);

  return [...previous, ...nextValues];
}

function relativeSort(rootDir: string, filePaths: string[]): string[] {
  return [...filePaths].map((filePath) => path.relative(rootDir, filePath)).sort();
}

function createAliasLookup(manifest: NormalizedManifest): Map<string, string> {
  const aliases = new Map<string, string>();

  for (const variable of Object.values(manifest.variables)) {
    for (const alias of variable.aliases) {
      aliases.set(alias, variable.key);
    }
  }

  return aliases;
}

async function analyzeWorkspaceEnv(
  rootDir: string,
  manifestInput: EnvManifest,
  options?: { targets?: string[] }
): Promise<WorkspaceAnalysis> {
  const manifest = normalizeManifest(manifestInput);
  const rootValues = await loadRootEnv(rootDir, manifest.sources);
  const sourceFiles = relativeSort(
    rootDir,
    (await Promise.all(manifest.sources.map(async (source) => {
      const sourcePath = path.resolve(rootDir, source);
      return (await fs.pathExists(sourcePath)) ? sourcePath : null;
    }))).filter((sourcePath): sourcePath is string => sourcePath !== null)
  );
  const selectedTargets = getRelevantTargets(manifest, sortedUnique(options?.targets || []));
  const aliasLookup = createAliasLookup(manifest);
  const usedCanonicalKeys = new Set<string>();
  const missingRequiredByTarget: Record<string, string[]> = {};
  const readyTargets: string[] = [];

    for (const targetName of selectedTargets) {
      const target = manifest.targets[targetName];
      const missing: string[] = [];

      for (const entry of target.entries) {
        usedCanonicalKeys.add(entry.source);
        const variable = manifest.variables[entry.source];
        const value = pickCanonicalValue(entry.source, variable, rootValues);
        if (entry.required && value === undefined) {
          missing.push(entry.source);
        }
      }

      missingRequiredByTarget[targetName] = missing;
      if (missing.length === 0) {
        readyTargets.push(targetName);
      }
    }

    const unknownRootKeys: string[] = [];
    const unusedRootKeys: string[] = [];
    for (const rootKey of Object.keys(rootValues).sort()) {
      const canonicalKey = manifest.variables[rootKey] ? rootKey : aliasLookup.get(rootKey);
      if (!canonicalKey) {
        unknownRootKeys.push(rootKey);
        continue;
      }

      if (!usedCanonicalKeys.has(canonicalKey)) {
        unusedRootKeys.push(rootKey);
      }
    }

    return {
      manifest,
      rootValues,
      sourceFiles,
      selectedTargets,
      readyTargets,
      missingRequiredByTarget,
      unknownRootKeys,
      unusedRootKeys
    };
}

export async function syncWorkspaceEnv(
  rootDir: string,
  manifest: EnvManifest,
  options?: { targets?: string[]; checkOnly?: boolean }
): Promise<SyncSummary> {
  const analysis = await analyzeWorkspaceEnv(rootDir, manifest, options);

  const changedFiles: string[] = [];
  const unchangedFiles: string[] = [];
  const missingRequired: string[] = [];

  for (const [targetName, missing] of Object.entries(analysis.missingRequiredByTarget)) {
    missingRequired.push(...missing.map((key) => `${targetName}:${key}`));
  }

  const targetNames = analysis.selectedTargets;
  for (const targetName of targetNames) {
    const target = analysis.manifest.targets[targetName];
    const targetEnvEntries: Array<{ key: string; value: string; description?: string }> = [];
    const targetExampleEntries: Array<{ key: string; value: string; description?: string }> = [];

    for (const entry of target.entries) {
      const variable = analysis.manifest.variables[entry.source];
      const value = pickCanonicalValue(entry.source, variable, analysis.rootValues);

      if (value !== undefined) {
        targetEnvEntries.push({ key: entry.target, value, description: variable.description });
      }

      const exampleValue = variable.example ?? (variable.secret ? '' : (value ?? ''));
      targetExampleEntries.push({ key: entry.target, value: exampleValue, description: variable.description });
    }

    const envPath = path.resolve(rootDir, target.outputFile);
    const examplePath = path.resolve(rootDir, target.exampleFile);

    const envChanged = await writeIfChanged(
      envPath,
      formatEnvFile(targetEnvEntries, `Runtime env for target ${targetName}`),
      options?.checkOnly === true
    );
    const exampleChanged = await writeIfChanged(
      examplePath,
      formatEnvFile(targetExampleEntries, `Example env for target ${targetName}`),
      options?.checkOnly === true
    );

    (envChanged ? changedFiles : unchangedFiles).push(path.relative(rootDir, envPath));
    (exampleChanged ? changedFiles : unchangedFiles).push(path.relative(rootDir, examplePath));
  }

  const rootExampleEntries = Object.keys(analysis.manifest.variables).sort().map((canonical) => {
    const variable = analysis.manifest.variables[canonical];
    const value = pickCanonicalValue(canonical, variable, analysis.rootValues);
    const exampleValue = variable.example ?? (variable.secret ? '' : (value ?? ''));

    return {
      key: canonical,
      value: exampleValue,
      description: variable.description
    };
  });

  const rootExamplePath = path.resolve(rootDir, analysis.manifest.rootExampleFile);
  const rootChanged = await writeIfChanged(
    rootExamplePath,
    formatEnvFile(rootExampleEntries, 'Canonical root env example'),
    options?.checkOnly === true
  );
  (rootChanged ? changedFiles : unchangedFiles).push(path.relative(rootDir, rootExamplePath));

  changedFiles.sort();
  unchangedFiles.sort();
  missingRequired.sort();

  return {
    sourceFiles: analysis.sourceFiles,
    touchedFiles: [...changedFiles, ...unchangedFiles].sort(),
    changedFiles,
    unchangedFiles,
    missingRequired
  };
}

export async function validateWorkspaceEnv(
  rootDir: string,
  manifest: EnvManifest,
  options?: { targets?: string[] }
): Promise<ValidationResult> {
  const analysis = await analyzeWorkspaceEnv(rootDir, manifest, options);
  const hasMissing = Object.values(analysis.missingRequiredByTarget).some((missing) => missing.length > 0);

  return {
    ok: !hasMissing,
    sourceFiles: analysis.sourceFiles,
    readyTargets: analysis.readyTargets,
    missingRequiredByTarget: analysis.missingRequiredByTarget,
    unknownRootKeys: analysis.unknownRootKeys,
    unusedRootKeys: analysis.unusedRootKeys
  };
}

function printHumanSyncSummary(summary: SyncSummary): void {
  console.log(`Sources: ${summary.sourceFiles.length > 0 ? summary.sourceFiles.join(', ') : '(none found)'}`);
  console.log(`Touched files: ${summary.touchedFiles.length}`);

  for (const filePath of summary.changedFiles) {
    console.log(`  changed   ${filePath}`);
  }
  for (const filePath of summary.unchangedFiles) {
    console.log(`  unchanged ${filePath}`);
  }

  if (summary.missingRequired.length > 0) {
    console.log('Missing required canonical variables:');
    for (const missing of summary.missingRequired) {
      console.log(`  - ${missing}`);
    }
  }
}

function printHumanValidation(result: ValidationResult): void {
  console.log(`Sources: ${result.sourceFiles.length > 0 ? result.sourceFiles.join(', ') : '(none found)'}`);

  for (const target of result.readyTargets) {
    console.log(`✅ ${target} ready`);
  }

  for (const [target, missing] of Object.entries(result.missingRequiredByTarget)) {
    if (missing.length === 0) continue;
    console.log(`❌ ${target} missing required: ${missing.join(', ')}`);
  }

  if (result.unknownRootKeys.length > 0) {
    console.log(`⚠️  Unknown root keys: ${result.unknownRootKeys.join(', ')}`);
  }

  if (result.unusedRootKeys.length > 0) {
    console.log(`ℹ️  Unused root keys: ${result.unusedRootKeys.join(', ')}`);
  }
}

const extension: VersioningExtension = {
  name: 'workspace-env',
  description: 'Workspace environment manifest management for monorepos',
  version: '1.0.0',

  register: async (program: Command, config: any) => {
    const extensionConfig: WorkspaceEnvConfig | undefined = config?.extensionConfig?.['workspace-env'];
    if (extensionConfig?.enabled === false) {
      return;
    }

    const env = program
      .command('env')
      .description('Workspace env manifest tools (sync, doctor, validate)');

    env
      .command('sync')
      .description('Generate target env files from canonical manifest')
      .option('-t, --target <id>', 'Target to process; repeat or use comma-separated values', collectTargetOption, [])
      .option('--check', 'Exit with non-zero code if generated files would change', false)
      .option('--json', 'Output machine-readable JSON summary', false)
      .action(async (options) => {
        const rootDir = process.cwd();
        const manifestPath = resolveManifestPath(rootDir, extensionConfig?.manifestPath);
        const manifest = await loadManifest(manifestPath);
        const targets = sortedUnique(options.target || []);
        const summary = await syncWorkspaceEnv(rootDir, manifest, {
          targets,
          checkOnly: options.check === true
        });

        if (options.json) {
          console.log(JSON.stringify(summary, null, 2));
        } else {
          printHumanSyncSummary(summary);
          console.log(`✅ env sync complete (${summary.changedFiles.length} changed, ${summary.unchangedFiles.length} unchanged)`);
        }

        if (options.check === true && summary.changedFiles.length > 0) {
          process.exit(1);
        }
      });

    env
      .command('doctor')
      .description('Check missing required vars and unknown root vars')
      .option('-t, --target <id>', 'Target to inspect; repeat or use comma-separated values', collectTargetOption, [])
      .option('--fail-on-missing', 'Exit with non-zero code if required vars are missing', false)
      .option('--json', 'Output machine-readable JSON report', false)
      .action(async (options) => {
        const rootDir = process.cwd();
        const manifestPath = resolveManifestPath(rootDir, extensionConfig?.manifestPath);
        const manifest = await loadManifest(manifestPath);
        const targets = sortedUnique(options.target || []);
        const result = await validateWorkspaceEnv(rootDir, manifest, { targets });

        if (options.json) {
          console.log(JSON.stringify(result, null, 2));
        } else {
          printHumanValidation(result);
          if (result.readyTargets.length === 0 && result.unknownRootKeys.length === 0 && result.unusedRootKeys.length === 0) {
            console.log('⚠️  No ready targets found.');
          }
        }

        const hasMissing = Object.values(result.missingRequiredByTarget).some((missing) => missing.length > 0);
        if (!hasMissing && !options.json) {
          console.log('✅ env doctor: no missing required variables');
        }

        if (hasMissing && options.failOnMissing) {
          process.exit(1);
        }
      });

    env
      .command('validate')
      .description('Validate env mapping (CI-friendly, fails on missing required vars)')
      .option('-t, --target <id>', 'Target to validate; repeat or use comma-separated values', collectTargetOption, [])
      .option('--all', 'Validate all targets explicitly', false)
      .option('--strict-unused', 'Fail if unknown or unused root keys are present', false)
      .option('--json', 'Output machine-readable JSON report', false)
      .action(async (options) => {
        const rootDir = process.cwd();
        const manifestPath = resolveManifestPath(rootDir, extensionConfig?.manifestPath);
        const manifest = await loadManifest(manifestPath);
        const targets = options.all === true ? undefined : sortedUnique(options.target || []);
        const result = await validateWorkspaceEnv(rootDir, manifest, { targets });
        const missing = Object.entries(result.missingRequiredByTarget).filter(([, vars]) => vars.length > 0);
        const hasStrictUnused = options.strictUnused === true && (result.unknownRootKeys.length > 0 || result.unusedRootKeys.length > 0);
        const ok = missing.length === 0 && !hasStrictUnused;

        if (options.json) {
          console.log(JSON.stringify({ ...result, ok }, null, 2));
        } else {
          printHumanValidation(result);
        }

        if (!ok) {
          process.exit(1);
        }

        if (!options.json) {
          console.log('✅ env validate: all required variables are available');
        }
      });
  }
};

export default extension;